project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - plots/**

  render:
    - index.qmd
    - visuals/*.qmd

website:
  title: "The Data Decoded"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: visuals/
        text: Visuals

format:
  html:
    theme: flatly
    toc: false
