project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - visuals/**/plots/**      # publish per-post images
    - assets/**

  render:
    - index.qmd
    - visuals/*.qmd

execute:
  dir: project

website:
  title: "The Data Decoded"
  navbar:
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
