project:
  type: website
  output-dir: docs
  resources:
    - plots/**

execute:
  dir: project
  code-after: |
    message("Running from: ", getwd())

website:
  title: "The Data Decoded"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: visuals/
        text: Visuals

format:
  html:
    theme: flatly
    toc: false
